<div class="post"><h2><a href="http://sourceforge.net/forum/forum.php?forum_id=625839">Yammy 0.9 UI Preview</a> <small>- Tue, 24 Oct 2006 13:31:18 GMT -</small></h2>
<div class="entry">
I've been promising a new UI for a long time. Guess what? I'm nearly done. Today I'll introduce some aspects of the new UI.<br /><br />Yammy 0.9 is different from its predecessors because it does not have its own UI. It borrows its UI from your web browser. Yammy comes with its own tiny webserver and it serves pages to your browser. (<a href="http://sourceforge.net/forum/forum.php?forum_id=625839">0 comments</a>)</div>
</div>
