/* Yammy 0.9 Language Resource File
 * (http://yammy.sourceforge.net)
 * 
 * Note to Translators:
 * - Please save this file in utf-8 format. To learn more about saving a file in utf-8, visit [TODO].
 * - & cause the next character to be underlined (Only for TrayMenuOpen, TrayMenuSettings, TraryMenuExit).
 * - {0}, {1}, {2}, etc are place holders which will be replaced by some data. Where ever they occur, an
 *   explaination is given with an example.
 * - Do fill in the Language, Name and Contact details.
 *
 * Language: English
 * Translator: Pravin Paratey
 * Contact: pravinp at gmail dot com
 *
 */

var AppName    = "Yammy"; // Do not edit
var AppVersion = "0.9"; // Do not edit

var TrayMenuOpen     = "&Open";
var TrayMenuSettings = "&Settings";
var TrayMenuExit     = "&Exit";

// ConversationBetween
// {0} -> local user-id
// {1} -> remote user-id.
// ex: Conversation between jack and jill
var ConversationBetween = "Conversation between {0} and {1}"; 

// ConversationStarted
// {0} -> date
// ex: Conversation started on January 26, 2007
var ConversationStarted = "Conversation started on {0}";

// NumSearchResults
// {0} -> starting number
// {1} -> total number
// ex. 11 of 2154 search results
var NumSearchResults = "{0} of {1} search results";

// SearchingFor
// {0} -> search term
// ex. Searching for apple
// TotalConvos
// {0} -> number
var TotalConvos = "Total conversations: {0}";

// LastConvo
// {0} -> Date
var LastConvo = "Last conversation: {0}";

// Archiving
// {0} -> this will be one of 'Enabled' or 'Disabled' depending on status
var Archiving = "Archiving: {0}";

// ShowingConvoFor
// {0} -> user-id
// ex. Showing conversations for Jack
var ShowingConvoFor = "Showing conversations for {0}";

var Error  = "Error"; // Generic error string
var Home   = "Home"; // Main page title
var More   = "More"; // Lets you view the whole conversation
var Hours  = "hrs"; // Settings: Lets you set the indexing frequency
var Users  = "Users"; // Local users on this system
var Search = "Search"; // Search button text
var Help   = "Help"; // Navigation: Takes you to the help page

var ViewLog  = "View Log"; // Navigation: Displays the log file
var Language = "Language"; // Option in Settings: Lets you select your display language
var PrevPage = "Previous Page"; // Takes you to the previous page while Searching or while browsing conversations
var NextPage = "Next Page"; 
var Settings = "Settings"; // Navigation: Takes you to the settings page

var UpdateFreq   = "Update Frequency";
var SaveSettings = "Save Settings";
var ExportConvos = "Export Conversations";
var NoIndexFound = "No index found!";
var FileNotFound = "File not found";
var NoConvoFound = "No conversations found";
var SearchingFor = "Searching for {0}"; // {0} -> search term
var VisitWebsite = "Visit Website";

var NoResultsFound    = "No results found"; // When searching for something returns no results
var ArchivingEnabled  = "Enabled";
var ArchivingEnable   = "Enable";   // Different from the above. This denotes the act of enabling
var ArchivingDisabled = "Disabled";
var ArchivingDisable  = "Disable";  // Different from the above. This denotes the act of disabling
var GeneratedByYammy  = "Generated by Yammy 0.9"; // The footer text
